from typing import Optional,List
from pydantic import BaseModel,Field


class LineItems(BaseModel):
    line_item_id: str

    part_number:Optional[str]=Field(default=None)
    part_number_confidence_score:Optional[float]=Field(default=None)
    part_number_page_number:Optional[int]=Field(default=None)
    part_number_x1_coordinate:Optional[float]=Field(default=None)
    part_number_y1_coordinate:Optional[float]=Field(default=None)
    part_number_x2_coordinate:Optional[float]=Field(default=None)
    part_number_y2_coordinate:Optional[float]=Field(default=None)
    part_number_x3_coordinate:Optional[float]=Field(default=None)
    part_number_y3_coordinate:Optional[float]=Field(default=None)
    part_number_x4_coordinate:Optional[float]=Field(default=None)
    part_number_y4_coordinate:Optional[float]=Field(default=None)

    unit_price:Optional[str]=Field(default=None)
    unit_price_confidence_score:Optional[float]=Field(default=None)
    unit_price_page_number:Optional[int]=Field(default=None)
    unit_price_x1_coordinate:Optional[float]=Field(default=None)
    unit_price_y1_coordinate:Optional[float]=Field(default=None)
    unit_price_x2_coordinate:Optional[float]=Field(default=None)
    unit_price_y2_coordinate:Optional[float]=Field(default=None)
    unit_price_x3_coordinate:Optional[float]=Field(default=None)
    unit_price_y3_coordinate:Optional[float]=Field(default=None)
    unit_price_x4_coordinate:Optional[float]=Field(default=None)
    unit_price_y4_coordinate:Optional[float]=Field(default=None)

    Total_Value:Optional[str]=Field(default=None)
    Total_Value_confidence_score:Optional[float]=Field(default=None)
    Total_Value_page_number:Optional[int]=Field(default=None)
    Total_Value_x1_coordinate:Optional[float]=Field(default=None)
    Total_Value_y1_coordinate:Optional[float]=Field(default=None)
    Total_Value_x2_coordinate:Optional[float]=Field(default=None)
    Total_Value_y2_coordinate:Optional[float]=Field(default=None)
    Total_Value_x3_coordinate:Optional[float]=Field(default=None)
    Total_Value_y3_coordinate:Optional[float]=Field(default=None)
    Total_Value_x4_coordinate:Optional[float]=Field(default=None)
    Total_Value_y4_coordinate:Optional[float]=Field(default=None)

    Quantity:Optional[str]=Field(default=None)
    Quantity_confidence_score:Optional[float]=Field(default=None)
    Quantity_page_number:Optional[int]=Field(default=None)
    Quantity_x1_coordinate:Optional[float]=Field(default=None)
    Quantity_y1_coordinate:Optional[float]=Field(default=None)
    Quantity_x2_coordinate:Optional[float]=Field(default=None)
    Quantity_y2_coordinate:Optional[float]=Field(default=None)
    Quantity_x3_coordinate:Optional[float]=Field(default=None)
    Quantity_y3_coordinate:Optional[float]=Field(default=None)
    Quantity_x4_coordinate:Optional[float]=Field(default=None)
    Quantity_y4_coordinate:Optional[float]=Field(default=None)

    country_of_origin:Optional[str]=Field(default=None)
    country_of_origin_confidence_score:Optional[float]=Field(default=None)
    country_of_origin_page_number:Optional[int]=Field(default=None)
    country_of_origin_x1_coordinate:Optional[float]=Field(default=None)
    country_of_origin_y1_coordinate:Optional[float]=Field(default=None)
    country_of_origin_x2_coordinate:Optional[float]=Field(default=None)
    country_of_origin_y2_coordinate:Optional[float]=Field(default=None)
    country_of_origin_x3_coordinate:Optional[float]=Field(default=None)
    country_of_origin_y3_coordinate:Optional[float]=Field(default=None)
    country_of_origin_x4_coordinate:Optional[float]=Field(default=None)
    country_of_origin_y4_coordinate:Optional[float]=Field(default=None)

    PO:Optional[str]=Field(default=None)
    PO_confidence_score:Optional[float]=Field(default=None)
    PO_page_number:Optional[int]=Field(default=None)
    PO_x1_coordinate:Optional[float]=Field(default=None)
    PO_y1_coordinate:Optional[float]=Field(default=None)
    PO_x2_coordinate:Optional[float]=Field(default=None)
    PO_y2_coordinate:Optional[float]=Field(default=None)
    PO_x3_coordinate:Optional[float]=Field(default=None)
    PO_y3_coordinate:Optional[float]=Field(default=None)
    PO_x4_coordinate:Optional[float]=Field(default=None)
    PO_y4_coordinate:Optional[float]=Field(default=None)

    ASN:Optional[str]=Field(default=None)
    ASN_confidence_score:Optional[float]=Field(default=None)
    ASN_page_number:Optional[int]=Field(default=None)
    ASN_x1_coordinate:Optional[float]=Field(default=None)
    ASN_y1_coordinate:Optional[float]=Field(default=None)
    ASN_x2_coordinate:Optional[float]=Field(default=None)
    ASN_y2_coordinate:Optional[float]=Field(default=None)
    ASN_x3_coordinate:Optional[float]=Field(default=None)
    ASN_y3_coordinate:Optional[float]=Field(default=None)
    ASN_x4_coordinate:Optional[float]=Field(default=None)
    ASN_y4_coordinate:Optional[float]=Field(default=None)


class Invoice(BaseModel):
    invoice_id:str

    invoice_number:Optional[str]=Field(default=None)
    invoice_number_confidence_score:Optional[float]=Field(default=None)
    invoice_number_page_number:Optional[int]=Field(default=None)
    invoice_number_x1_coordinate:Optional[float]=Field(default=None)
    invoice_number_y1_coordinate:Optional[float]=Field(default=None)
    invoice_number_x2_coordinate:Optional[float]=Field(default=None)
    invoice_number_y2_coordinate:Optional[float]=Field(default=None)
    invoice_number_x3_coordinate:Optional[float]=Field(default=None)
    invoice_number_y3_coordinate:Optional[float]=Field(default=None)
    invoice_number_x4_coordinate:Optional[float]=Field(default=None)
    invoice_number_y4_coordinate:Optional[float]=Field(default=None)

    Incoterm:Optional[str]=Field(default=None)
    Incoterm_confidence_score:Optional[float]=Field(default=None)
    Incoterm_page_number:Optional[int]=Field(default=None)
    Incoterm_x1_coordinate:Optional[float]=Field(default=None)
    Incoterm_y1_coordinate:Optional[float]=Field(default=None)
    Incoterm_x2_coordinate:Optional[float]=Field(default=None)
    Incoterm_y2_coordinate:Optional[float]=Field(default=None)
    Incoterm_x3_coordinate:Optional[float]=Field(default=None)
    Incoterm_y3_coordinate:Optional[float]=Field(default=None)
    Incoterm_x4_coordinate:Optional[float]=Field(default=None)
    Incoterm_y4_coordinate:Optional[float]=Field(default=None)

    commercial_invoice_value:Optional[str]=Field(default=None)
    commercial_invoice_value_confidence_score:Optional[float]=Field(default=None)
    commercial_invoice_value_page_number:Optional[int]=Field(default=None)
    commercial_invoice_value_x1_coordinate:Optional[float]=Field(default=None)
    commercial_invoice_value_y1_coordinate:Optional[float]=Field(default=None)
    commercial_invoice_value_x2_coordinate:Optional[float]=Field(default=None)
    commercial_invoice_value_y2_coordinate:Optional[float]=Field(default=None)
    commercial_invoice_value_x3_coordinate:Optional[float]=Field(default=None)
    commercial_invoice_value_y3_coordinate:Optional[float]=Field(default=None)
    commercial_invoice_value_x4_coordinate:Optional[float]=Field(default=None)
    commercial_invoice_value_y4_coordinate:Optional[float]=Field(default=None)

    supplier_name:Optional[str]=Field(default=None)
    supplier_name_confidence_score:Optional[float]=Field(default=None)
    supplier_name_page_number:Optional[int]=Field(default=None)
    supplier_name_x1_coordinate:Optional[float]=Field(default=None)
    supplier_name_y1_coordinate:Optional[float]=Field(default=None)
    supplier_name_x2_coordinate:Optional[float]=Field(default=None)
    supplier_name_y2_coordinate:Optional[float]=Field(default=None)
    supplier_name_x3_coordinate:Optional[float]=Field(default=None)
    supplier_name_y3_coordinate:Optional[float]=Field(default=None)
    supplier_name_x4_coordinate:Optional[float]=Field(default=None)
    supplier_name_y4_coordinate:Optional[float]=Field(default=None)
    
    supplier_location:Optional[str]=Field(default=None)
    supplier_location_confidence_score:Optional[float]=Field(default=None)
    supplier_location_page_number:Optional[int]=Field(default=None)
    supplier_location_x1_coordinate:Optional[float]=Field(default=None)
    supplier_location_y1_coordinate:Optional[float]=Field(default=None)
    supplier_location_x2_coordinate:Optional[float]=Field(default=None)
    supplier_location_y2_coordinate:Optional[float]=Field(default=None)
    supplier_location_x3_coordinate:Optional[float]=Field(default=None)
    supplier_location_y3_coordinate:Optional[float]=Field(default=None)
    supplier_location_x4_coordinate:Optional[float]=Field(default=None)
    supplier_location_y4_coordinate:Optional[float]=Field(default=None)

    HAWB_number:Optional[str]=Field(default=None)
    HAWB_number_confidence_score:Optional[float]=Field(default=None)
    HAWB_number_page_number:Optional[int]=Field(default=None)
    HAWB_number_x1_coordinate:Optional[float]=Field(default=None)
    HAWB_number_y1_coordinate:Optional[float]=Field(default=None)
    HAWB_number_x2_coordinate:Optional[float]=Field(default=None)
    HAWB_number_y2_coordinate:Optional[float]=Field(default=None)
    HAWB_number_x3_coordinate:Optional[float]=Field(default=None)
    HAWB_number_y3_coordinate:Optional[float]=Field(default=None)
    HAWB_number_x4_coordinate:Optional[float]=Field(default=None)
    HAWB_number_y4_coordinate:Optional[float]=Field(default=None)

    MAWB_number:Optional[str]=Field(default=None)
    MAWB_number_confidence_score:Optional[float]=Field(default=None)
    MAWB_number_page_number:Optional[int]=Field(default=None)
    MAWB_number_x1_coordinate:Optional[float]=Field(default=None)
    MAWB_number_y1_coordinate:Optional[float]=Field(default=None)
    MAWB_number_x2_coordinate:Optional[float]=Field(default=None)
    MAWB_number_y2_coordinate:Optional[float]=Field(default=None)
    MAWB_number_x3_coordinate:Optional[float]=Field(default=None)
    MAWB_number_y3_coordinate:Optional[float]=Field(default=None)
    MAWB_number_x4_coordinate:Optional[float]=Field(default=None)
    MAWB_number_y4_coordinate:Optional[float]=Field(default=None)

    line_items:Optional[List[LineItems]]=Field(default=None)

    currency:Optional[str]=Field(default=None)
    currency_confidence_score:Optional[float]=Field(default=None)
    currency_page_number:Optional[int]=Field(default=None)
    currency_x1_coordinate:Optional[float]=Field(default=None)
    currency_y1_coordinate:Optional[float]=Field(default=None)
    currency_x2_coordinate:Optional[float]=Field(default=None)
    currency_y2_coordinate:Optional[float]=Field(default=None)
    currency_x3_coordinate:Optional[float]=Field(default=None)
    currency_y3_coordinate:Optional[float]=Field(default=None)
    currency_x4_coordinate:Optional[float]=Field(default=None)
    currency_y4_coordinate:Optional[float]=Field(default=None)

    reviewed_by:Optional[str]=Field(default=None)
    review_date:Optional[str]=Field(default=None)
    created_by:Optional[str]=Field(default=None)
    original_creation_date:Optional[str]=Field(default=None)
    last_updated_date:Optional[str]=Field(default=None)
    reason_or_remarks:Optional[str]=Field(default=None)
    minimum_confidence:Optional[float]=Field(default=None)
    status:Optional[str]=Field(default=None)


class AllInvoices(BaseModel):
    invoice_id:str
    invoice_number:Optional[str]=Field(default=None)
    original_creation_date:Optional[str]=Field(default=None)
    status:Optional[str]=Field(default=None)
    review_date:Optional[str]=Field(default=None)
    reviewed_by:Optional[str]=Field(default=None)
    minimum_confidence:Optional[float]=Field(default=None)
    aging:Optional[int]=Field(default=None)


class Cancel_invoice(BaseModel):
    invoice_id:str
    status:str